export const GAME_CONSTANTS = {
  DRAW_TIME_SECONDS: 60,
  REVEAL_TIME_SECONDS: 15,
  VOTE_TIME_SECONDS: 20,
  JUDGE_TIME_SECONDS: 5,
  RESULTS_TIME_SECONDS: 10,
  MAX_PLAYERS: 8,
  MIN_PLAYERS: 4,
  ROUNDS_PER_MATCH: 5,
};
